### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by pascalwengerter** [codecurious-bln/CC-website#12]
Introduce German and English language segmentation. 

`/de/impressum` for german page, and `/about` for english.

**Comment by carlad** [comment]
Is there any copy for what should be on the /de/impressum page?

Is it a copy of this? http://codecurious.org/impressum/

Also, do you want DE and EN language translations for every page?

**Comment by ferbsx** [comment]
@carlad Yes, the link is the text we want on the impressum page, except for the contact email, which should be changed from `contact@railsgirlsberlin.de` to `contact@codecurious.org`.

We would love a German and English translation of all our pages but I don't think that is worth the work for all our older blogs, press stories,...

Our main language should be English and all content should be available in EN.
