### ISSUE TITLE
Add a contributor code of conduct for GitHub 

### ISSUE THREAD

**Issue by ferbsx** [codecurious-bln/CC-website#21]

**Comment by 25th-bam** [comment]
@ferbsx, I would like to take this, is using https://www.contributor-covenant.org fine with you?

**Comment by ferbsx** [comment]
@25th-bam I was thinking of using the Citizen code of conduct since it is more relevant for us (as we also have live events which that code of conduct better covers) and am actually already editing it with contact info. I'm sorry I didn't assign it to myself.
