### ISSUE TITLE
Update German text of Rails Beginner Workshop

### ISSUE THREAD

**Issue by shushugah** [codecurious-bln/CC-website#50]
This is the file that must be updated. A Code of Conduct is already included (A german version should be made, as a separate PR). To see what the english file looks like, see [here](https://github.com/codecurious-bln/CC-website/blob/master/en/_posts/2019-12-07-rails-beginner-workshop.markdown). 

https://github.com/codecurious-bln/CC-website/blob/master/de/_posts/2019-12-07-rails-beginner-workshop.markdown

**Comment by ferbsx** [comment]
Setting up a draft now :)
